<?php
// Automatically Generated by TestLink Installer - Wed, 10 Apr 24 00:39:50 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.1.50');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
